"""Dendros: a Python toolkit for analyzing Galacticus semi-analytic model outputs."""
from __future__ import annotations

from ._analyses import list_analyses, plot_analyses
from ._collection import Collection, ModelCollection, open_models, open_outputs
from ._galaxy_history import trace_galaxy_history
from ._mcmc import (
    Chain,
    ChainSet,
    EnsembleDriftResult,
    InflationResult,
    JacobianFit,
    LEGACY_SAMPLE_STEP_OFFSET,
    LOG_IMPROBABLE,
    Likelihood,
    MCMCConfig,
    MCMCRun,
    MVNFit,
    MaxResult,
    ModelParameter,
    PairedPredictions,
    PerturberSpec,
    PosteriorSamples,
    PredictionSeries,
    PredictionSet,
    PriorSpec,
    ProjectionPursuitResult,
    ProposalSeries,
    ProposalSet,
    RhatResult,
    SAMPLE_STEP_OFFSETS,
    acceptance_rate,
    acceptance_rate_trace,
    apply_state,
    autocorrelation_function,
    autocorrelation_time,
    convergence_step,
    corner_plot,
    count_variance,
    discover_prediction_labels,
    discover_proposal_files,
    dodelson_schneider_factor,
    effective_sample_size,
    emit_parameter_files,
    ensemble_drift,
    fisher_matrix,
    fisher_weights,
    gelman_rubin,
    geweke,
    hartlap_factor,
    index_prediction_files,
    information_shares,
    jacobian_from_samples,
    log_likelihood_bins,
    maximum_likelihood,
    maximum_posterior,
    multivariate_normal_fit,
    nearest_positive_definite,
    negative_binomial_shape,
    open_mcmc,
    outlier_chains,
    parameter_covariances,
    parse_mcmc_config,
    posterior_samples,
    projection_pursuit,
    read_chains,
    read_parameter_file,
    read_predictions,
    read_proposals,
    rescale_correlation,
    resolve_parameter_path,
    shrink_to_diagonal,
    to_correlation,
    write_parameter_file_to,
)
from ._outputs import OutputIndex, OutputMeta
from ._star_formation import sfh_collapse_metallicities, sfh_times

try:
    from importlib.metadata import PackageNotFoundError, version as _version

    __version__ = _version("dendros")
except PackageNotFoundError:  # package is not installed
    __version__ = "0.0.0+unknown"

__all__ = [
    "count_variance",
    "Chain",
    "ChainSet",
    "Collection",
    "EnsembleDriftResult",
    "InflationResult",
    "JacobianFit",
    "LOG_IMPROBABLE",
    "Likelihood",
    "MCMCConfig",
    "MCMCRun",
    "MVNFit",
    "MaxResult",
    "ModelCollection",
    "ModelParameter",
    "OutputIndex",
    "OutputMeta",
    "PairedPredictions",
    "PerturberSpec",
    "PosteriorSamples",
    "PredictionSeries",
    "PredictionSet",
    "ProposalSeries",
    "ProposalSet",
    "PriorSpec",
    "ProjectionPursuitResult",
    "RhatResult",
    "SAMPLE_STEP_OFFSETS",
    "LEGACY_SAMPLE_STEP_OFFSET",
    "acceptance_rate",
    "acceptance_rate_trace",
    "apply_state",
    "autocorrelation_function",
    "autocorrelation_time",
    "convergence_step",
    "corner_plot",
    "discover_prediction_labels",
    "discover_proposal_files",
    "index_prediction_files",
    "dodelson_schneider_factor",
    "effective_sample_size",
    "emit_parameter_files",
    "ensemble_drift",
    "fisher_matrix",
    "fisher_weights",
    "gelman_rubin",
    "geweke",
    "hartlap_factor",
    "information_shares",
    "jacobian_from_samples",
    "list_analyses",
    "log_likelihood_bins",
    "maximum_likelihood",
    "maximum_posterior",
    "multivariate_normal_fit",
    "nearest_positive_definite",
    "negative_binomial_shape",
    "open_mcmc",
    "open_models",
    "open_outputs",
    "outlier_chains",
    "parameter_covariances",
    "parse_mcmc_config",
    "plot_analyses",
    "posterior_samples",
    "projection_pursuit",
    "read_chains",
    "read_parameter_file",
    "read_predictions",
    "read_proposals",
    "rescale_correlation",
    "resolve_parameter_path",
    "sfh_collapse_metallicities",
    "sfh_times",
    "shrink_to_diagonal",
    "to_correlation",
    "trace_galaxy_history",
    "write_parameter_file_to",
]
